### ISSUE TITLE
missing dependency 

### ISSUE THREAD

**Issue by Keld312** [wiomoc/iap2#2]
Hi,

I had a look on your repo and thank you for this nice project and explanation on the blog. I would like to test it for my own needs on my PI but I don’t find the iap2.carplay_bonjour lib. 
Could you tell please me where I can find it ?

BR,
RaspExt

**Comment by hbouhadji** [comment]
+1 @wiomoc

**Comment by Keld312** [comment]
Thank you @wiomoc for this commit.
I forgot to tell you about iap2.rtsc_server.
Do you want a new ticket ?
Thank you in advance for your answer.

**Comment by wiomoc** [comment]
The airplay part doesnt work use an implementation like https://github.com/openairplay/airplay2-receiver
